### ISSUE TITLE
Unexpected type '' encountered while reading 'action manifest root'. The type 'MappingToken' was expected.

### ISSUE THREAD

**Issue by codaamok** [TravisSpomer/deploy-to-azure-storage#2]
```
Current runner version: '2.273.5'
Operating System
Virtual Environment
Prepare workflow directory
Prepare all required actions
Getting action download info
Download action repository 'actions/checkout@v2'
Download action repository 'peaceiris/actions-hugo@v2'
Download action repository 'TravisSpomer/deploy-to-azure-storage@v1.1'
Error: TravisSpomer/deploy-to-azure-storage/v1.1/action.yml:
Error: TravisSpomer/deploy-to-azure-storage/v1.1/action.yml: (Line: 20, Col: 124, Idx: 758) - (Line: 20, Col: 171, Idx: 805): While parsing a block mapping, did not find expected key.
Error: System.ArgumentException: Unexpected type '' encountered while reading 'action manifest root'. The type 'MappingToken' was expected.
   at GitHub.DistributedTask.ObjectTemplating.Tokens.TemplateTokenExtensions.AssertMapping(TemplateToken value, String objectDescription)
   at GitHub.Runner.Worker.ActionManifestManager.Load(IExecutionContext executionContext, String manifestFile)
Error: Fail to load TravisSpomer/deploy-to-azure-storage/v1.1/action.yml
```

I don't know JS very well, but would the issue stem [from this line](https://github.com/TravisSpomer/deploy-to-azure-storage/blob/main/action.yml#L20)? The apostrophe on the contracted word `you're`.

**Comment by SJEIadministrator** [comment]
I am also facing the same issue @codaamok

**Comment by TravisSpomer** [comment]
Oh, my apologies for missing this. Fixed in the latest version.
